-- MySQL Script generated by MySQL Workbench
-- Tue Dec  6 10:08:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pracownicy` (
  `idpracownicy` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  PRIMARY KEY (`idpracownicy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`j.programowania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `j.programowania` (
  `idj.programowania` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`idj.programowania`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obce` (
  `idobce` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`idobce`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obce_pracownika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obce_pracownika` (
  `pracownicy_idpracownicy` INT NOT NULL,
  `obce_idobce` INT NOT NULL,
  PRIMARY KEY (`pracownicy_idpracownicy`, `obce_idobce`),
  FOREIGN KEY (idpracownicy) REFERENCES pracownicy(idpracownicy),
  FOREIGN KEY (idobce) REFERENCES obce(idobce)
);
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pracownicy_j.programowania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pracownicy_j.programowania` (
  `pracownicy_idpracownicy` INT NOT NULL,
  `idj.programowania` INT NOT NULL,
  PRIMARY KEY (`pracownicy_idpracownicy`, `idj.programowania`),
  FOREIGN KEY (idpracownicy) REFERENCES pracownicy(idpracownicy),
  FOREIGN KEY (idj.programowania) REFERENCES j.programowania(idj.programowania)
);
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
